### PR TITLE
Add notes for community call on 2023-04-18.

### PR DESCRIPTION
**Pull request by mkcor**
Hi @stefanv, @lagru, and @jarrodmillman,

I have read the latest meeting notes to keep me up-to-date. Since I wasn't there, I don't actually know who was present! Please edit to reflect the truth. :smile: 

I have changed the spacing convention around slashes: I'm using no whitespace when the alternative/association is between only the word right before and the word right after (A/B, as exemplified in the above); I'm using spaces when it's between a group of words, as in {this little chunk} / {that other chunk}. But maybe the standard convention is the other way around? :thinking:

### CODE REVIEW

**Comment by stefanv** [comment]
Present: Jarrod Millman and Stéfan van der Walt. Thanks!

**Comment by stefanv** [comment]
Presumably this was the Pacific / American meeting, otherwise Lars would have attended.

**Comment by mkcor** [comment]
> Presumably this was the Pacific / American meeting, otherwise Lars would have attended.

Then, I presume the time wasn't actually 17:00 – 18:00 UTC? I copied-pasted it from the HackMD, but since the date was off, maybe the time was too?

**Comment by stefanv** [comment]
Ah, woops, I just clicked on the calender linked and edited. The meeting was 4pm Pacific.

**Comment by stefanv** [comment]
Thank you, @mkcor!

**Pull request merged**
