### PR TITLE
notes of Atlantic meeting

### PR DESCRIPTION
**Pull request by emmanuelle**

### CODE REVIEW

**Comment by sciunto** [comment]
I can't merge... :/

**Comment by emmanuelle** [comment]
@sciunto you don't have merge rights for this repo? Let me see if I can fix this.

**Comment by sciunto** [comment]
Nope, I don't have the rights.

**Comment by emmanuelle** [comment]
you should have received an invitation

**Comment by sciunto** [comment]
Perfect! Thanks @emmanuelle

**Pull request merged**
